### ISSUE TITLE
可以增加设置下划线颜色的方法吗

### ISSUE THREAD

**Issue by LxzBUG** [CNCoderX/WheelView#1]

**Comment by CNCoderX** [comment]
分割线样式可以在xml中通过app:divider设置，或者代码中调用setDivider方法



654833536@qq.com
 
发件人： LxzBUG
发送时间： 2018-03-01 12:07
收件人： CNCoderX/WheelView
抄送： Subscribed
主题： Re: [CNCoderX/WheelView] 可以增加设置下划线颜色的方法吗 (#1)
Closed #1.
